import {
  Flex,
  useColorModeValue,
  Box,
  Stack,
  Text,
  Link,
  Icon,
  IconButton,
} from "@chakra-ui/react";
import Head from "next/head";
import { useState } from "react";
import LeftSidebar from "../components/leftSidebar";
import Login from "../components/login";
import MainContent from "../components/mainContent";
import RightSidebar from "../components/rightSidebar";

export default function Home() {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex minH="100vh">
        {(isLoggedIn && (
          <>
            <LeftSidebar></LeftSidebar>
            <MainContent></MainContent>
            <RightSidebar />
          </>
        )) || <Login />}
      </Flex>
    </div>
  );
}
